### ISSUE TITLE
Lots of spaces in <tr> class attribute

### ISSUE THREAD

**Issue by redsPL** [ewhal/nyaa#101]
Something adds a lot of spaces in the class attribute, example:
![spaaaace](https://cloud.githubusercontent.com/assets/22369758/25774630/cf3db8d6-3293-11e7-8205-0f3e377a117d.png)
You can reproduce it by inspecting any element in the torrent list.

**Comment by ZoneSix** [comment]
From the looks of things. I'm suspecting it's the whitespace before all the golang code.

**Comment by redsPL** [comment]
OK, so i've been told that this happens due to templating and it's not a bug. I'm closing the issue.
