### ISSUE TITLE
404 page suggestions

### ISSUE THREAD

**Issue by redsPL** [ewhal/nyaa#105]
On IRC we discussed making a custom 404 page. Original nyaa had a 403 page with [a cute miku](http://web.archive.org/web/20170424234112/https://www.nyaa.se/favicon.ico) (probably something similiar on 404 page but i'm not able to retrieve that one); As the new page is more Megumin/Renchon themed, we should pick a new one. Please send your suggestions in this issue.

My suggestion:
![disappointedmegu_nobackground](https://cloud.githubusercontent.com/assets/22369758/25775072/f233c610-329c-11e7-8ff4-8109c9c6b9dd.png)
(ofc this would need to be completely redone from scratch, but i can do it)

**Comment by sfan5** [comment]
suggestion by @akuma06 
![](http://skythewoodtl.com/wp-content/uploads/2016/04/1458166214295.png)

**Comment by nitori** [comment]
!["Renge 404"](https://rawgithub.com/nitori/pynyaa/master/pynyaa/assets/static/img/renge.svg "Renge 404")

**Comment by sfan5** [comment]
omg how do you keep doing this

maybe we can have megu as 404 in night mode and renge-chan for normal theme?

**Comment by kipukun** [comment]
I like that @sfan5. Wouldn't be difficult to implement that.

**Comment by redsPL** [comment]
@sfan5 i can do that, nice idea :)
