### ISSUE TITLE
New site don't support unicode

### ISSUE THREAD

**Issue by egozi44** [ewhal/nyaa#107]
So my Utorrent is not in English (and so my system) and each time I add magnet link only from you guys, each line that been wrote in Japanese latters will be shown as question mark in my uTorrent, 

It seem to happend only for the magnet part (at least for now, need to check stuff with other torrents) as once it changed to the torrent everything look alright. 

The thing is that it never happened to me before on any site, is this thing can be fixed or it just how things will be from today onward?

**Comment by sfan5** [comment]
*Works for me*

Website:
![site](https://cloud.githubusercontent.com/assets/1042418/25775538/8ae12f7e-32a7-11e7-8362-79634dbc9de9.png)

Torrent client:
![client](https://cloud.githubusercontent.com/assets/1042418/25775540/9257d258-32a7-11e7-914f-f89fded34f7b.png)

**Comment by aerojun** [comment]
@egozi44 could you upload a screenshot?

It works for me too.

**Comment by S0X-LT** [comment]
Works for me also.

Also ditch utorrent, it is considered unsafe (unless you're using 2.2.1) and use [qBittorrent](https://www.qbittorrent.org/) instead.

**Comment by akuma06** [comment]
I have locales in Japanese and that works too. Could you give us some screenshots ?

**Comment by egozi44** [comment]
I use utorrent 2.2.1 (which is also not considered safe enough unlike qBittorrent)

Here image (Cen the language for my privacy xD )

[Image]http://oi64.tinypic.com/2z4y0s1.jpg[/Image]

I have Japanese language pack installed and never had such Unicode issue with utorrent so far

**Comment by MasterCATZ** [comment]
Deluge did it for me as well 
[IMG]http://i64.tinypic.com/5y9l5e.png[/IMG]
checking my language packs now unsure if it's local or remote ( servers in France )

**Comment by sfan5** [comment]
@egozi44 
It looks like your utorrent tries to decode unicode as windows-1252 or similar.
This is most likely a bug in uTorrent.

**Comment by kipukun** [comment]
Works for me as well on Deluge 1.3.13 and qBittorrent 3.3.1
Seems this is an issue with uTorrent.

**Comment by egozi44** [comment]
The thing is that it never happend to me before on any site, not with old nyaa as well, it small issue though so I don't know if anyone need to bother.... it just look broken xD

**Comment by ewhal** [comment]
is this a utorrent bug?
You shouldn't be using uTorrent in general better FOSS alternatives exist that don't contain bitcoin miners
