### ISSUE TITLE
Grabbing old and recent torrents from the wayback machine

### ISSUE THREAD

**Issue by belldandu** [ewhal/nyaa#112]
Earlier i read somewhere about people not being able to get past page 1000 when scraping stuff from before 2010. 
So i raise you these in the hopes that you may be able to scrape some recent stuff and old stuff from it.
https://web.archive.org/web/*/nyaa.se
https://web.archive.org/web/*/sukebei.nyaa.se
https://web.archive.org/web/*/nyaatorrents.org
https://web.archive.org/web/*/sukebei.nyaatorrents.org
https://web.archive.org/web/*/nyaa.eu
https://web.archive.org/web/*/sukebei.nyaa.eu

All of the torrent links and magnet hashes appear to work (i.e. torrent files are downloadable). 
Earliest snapshot of nyaa.se is 2012 and the latest is april 30 2017. 
Earliest snapshot of sukebei.nyaa.se is 2013 and latest is april 30 2017.
Earliest snapshot of nyaatorrents.org is 2006 and latest is april 30 2017.
Earliest snapshot of sukebei.nyaatorrents.org is 2008 and latest is april 30 2017.
Earliest snapshot of nyaa.eu is 2011 and latest is april 30 2017.
Earliest snapshot of sukebei.nyaa.eu is 2011 and latest is april 30 2017.

**Comment by S0X-LT** [comment]
Nyaa db is up to date until a few mins until shutdown, it's only 1 year of sukebei that has been lost, but someone managed to recover the torrents from that year (sans JAV stuff, however).

And no, you can't use wayback machine to grab the torrents. just try clicking one, it doesn't store them.

**Comment by MasterCATZ** [comment]
@belldandu 
umm the database is good till 23 June 2008
and even images going back to at least 2014 .. gave up looking for something older  ..

http://tinypic.com/r/35d6fph/9

**Comment by belldandu** [comment]
@S0X-LT i click a couple of them and the files downloaded. You probably ran into a 504 bad gateway error which the wayback machine is famous for. https://web.archive.org/web/20140807225427/http://www.nyaa.se/?page=download&tid=585076 downloads fine for me.

@MasterCATZ awesome.

@akuma06 this should at least stay open for the ones that are missing.

**Comment by belldandu** [comment]
Also @MasterCATZ what about the 2006 stuff. https://web.archive.org/web/20071012105535/http://www.nyaatorrents.org/?page=download&tid=3863
https://web.archive.org/web/20061202025456/http://nyaatorrents.org:80/?page=torrents

**Comment by MasterCATZ** [comment]
oh I didn't even think about the orig site 

I wounder if I have the backups from that as well sitting around here :P 
all I  know is a quick glace I had like 3 mil nyaa torrents sitting on my seedbox's
