### ISSUE TITLE
Magnets dissapearing???

### ISSUE THREAD

**Issue by VermillionM** [ewhal/nyaa#130]
So there were some SDF Macross batches some hours ago, but now I'm looking for them and they aren't there. is this a problem with the database (sorry, not informed on the actual naming) or what? They are like the only ones working  anywhere for this series (>;_;)>

**Comment by ewhal** [comment]
do you have any links to the page?

**Comment by VermillionM** [comment]
Nope, could've bookmarked the search page but my past self was an idiot and chose not do so. Still weird though, the only Macross thing appearing is a song and that's it.

**Comment by lc-guy** [comment]
can you check your history?

**Comment by VermillionM** [comment]
(I erased my history for eh, reasons)
But anyways looks like it's back, thanks o/
