### ISSUE TITLE
404 page doesn't appear if the directory the page is in exists

### ISSUE THREAD

**Issue by redsPL** [ewhal/nyaa#135]
Custom 404 works, but only when you try a page on root that doesn't exist (such as "/asdfasfasf"). Old 404 appears, if you try a page in directory css, js or img(such as "/img/asdfasdfasfd").

**Comment by Atvaark** [comment]
[These handlers](https://github.com/ewhal/nyaa/blob/6e33a2fe7f24877fd17df9ac4607b5c30ed42ac3/router/router.go#L18-L20) match every route with a css/js/img prefix and return the default 404 response. The *NotFoundHandler* will only be used when no route was found.

```
http.Handle("/css/", http.StripPrefix("/css/", cssHandler))
http.Handle("/js/", http.StripPrefix("/js/", jsHandler))
http.Handle("/img/", http.StripPrefix("/img/", imgHandler))
```

If you want to return the custom 404 page you'd have to wrap the handler with a customized one that checks if [http.ResponseWriter.WriteHeader(int)](https://github.com/golang/go/blob/53003621720ff39c4745a76f76847123c27b01ea/src/net/http/server.go#L139) got called with *http.StatusNotFound*.

**Comment by SpamNeko** [comment]
[https://github.com/ewhal/nyaa/pull/236](https://github.com/ewhal/nyaa/pull/236)

**Comment by ayame-git** [comment]
^
