### ISSUE TITLE
Search Function doesn't quite work

### ISSUE THREAD

**Issue by regi4** [ewhal/nyaa#152]
I noticed this while searching for older series, but the search function doesn't function properly. I tried searching for the latest torrent that was uploaded before the ship sank, and it can't even return at least that result.

http://puu.sh/vIEzq/f0a306a9bd.png

I don't have much experience with coding, so I don't know what to test for, but I am willing to help.

**Comment by majestrate** [comment]
it seems to be case sensative right now

**Comment by regi4** [comment]
Thank you! I'll be sure to let people know before they try to use this site.

**Comment by sfan5** [comment]
This might be caused by postgres, search is case-<b>in</b>sensitive with sqlite

**Comment by ayame-git** [comment]
Fixed I don't even remember how long  ago
