### ISSUE TITLE
Subaki's image category not fit the file

### ISSUE THREAD

**Issue by egozi44** [ewhal/nyaa#162]
So I assume that subaki still underwork since it under heavy load most of the time and still don't have updated database (and may never will :( )

But I noticed some bug that may be worth reporting. it seem that the image category don't fit the file, let say I look for random H game, it will find it but will be under looseless audio categorey

![hgfhf](https://cloud.githubusercontent.com/assets/14190834/25784809/328a8ade-337c-11e7-9302-e4fff28a4343.PNG)

I think the serach option is also a bit buggy but I saw that it was already mentioned in other thread

**Comment by ewhal** [comment]
Added to TODO
