### ISSUE TITLE
Allow uploader to take ownership of their old account/torrents

### ISSUE THREAD

**Issue by yiiTT** [ewhal/nyaa#174]
On nyaa there were a handful of primary uploaders, this feature would allow an uploader to link their old user with their new one or restore their old account. 

An uploader is required to verify that they own the old user by release website, forum profile (anime-sharing, 2djgame, mikocon, etc), IRC, twitter, etc by looking at their history and require a verification post or message on said website. The verification process will be verified by 2 or more moderators.

The uploader can request this feature via IRC. (help channel?)

All Existing torrents should be locked to would prevent malicious users that got past the verifying process or are now malicious from modifying torrents.

Methods
1. account restored, no changes needed.
2. When you visit the new or old user profile it will display both user's torrents.
3. redirect old user id to new one and display both user's torrents on new account.
4. have a better idea?

Whats your ideas for displaying older torrents for users that "imported" their accounts? (2,3)

A step into the future by going back.

**Comment by ewhal** [comment]
Definitely want to support the ability for groups to take control of their old torrents.

**Comment by azhao12345** [comment]
I don't see the uploaders for the torrents in the current database dump, so we'll need to get those first.

**Comment by MaeJhem** [comment]
Yeah, I don't see the uploads for the torrents in your database.
How about creating a "recover account" using email.

**Comment by willi123yao** [comment]
We can certainly get most of the uploaders from archives if the page is archived that it

**Comment by MaeJhem** [comment]
But, that's kinda impossible. There's some users that upload their own torrents as "anonymous". and the torrents show on their profile page.

**Comment by yiiTT** [comment]
> How about creating a "recover account" using email.
@MaeJhem Yea but that would not work for recovering an account from the dump since it does not have user emails. But that is the plan for new accounts.

> I don't see the uploaders for the torrents in the current database dump, so we'll need to get those first.
> We can certainly get most of the uploaders from archives if the page is archived that it
@azhao12345 @willi123yao ilikecats has the dump with users still in it, so there is no need to worry about that. We just need him to upload it and we got it.

**Comment by MaeJhem** [comment]
@yiiTT That would be interesting..

**Comment by sfan5** [comment]
[applies to new schema only, see #184]
Old accounts will not be stored alongside new accounts in the same table. In fact they won't be stored at all.
Reassigning all previous torrents to a new user will just be a SQL statement away.
