### ISSUE TITLE
Consolidating FrontEnd Efforts.

### ISSUE THREAD

**Issue by Jiro-Horikoshi** [ewhal/nyaa#177]
1. **Anyone interested in assisting with any aspect of the frontend development** pertaining to Nyaa's revival should mail jiro.horikoshi1@gmail.com so we can better coordinate efforts. Communications will most likely take place through discord.

2. For easier reference by the frontend team as a whole, I'd like to request that all new feature requests / upgrades from old nyaa / fixes be commented to [this document.](https://docs.google.com/document/d/1MgAPqrVqggXji7EqdH8EcRuew83uZoEkGrSCDjhcXMI/edit?usp=sharing)

3. **Individuals should still make separate issue threads for each new idea, feature, upgrade request etc so they can easily be seen by the community here.**

Cheers for free media.

**Comment by ewhal** [comment]
This is way out of scope of the current project.
If you want to work on such a project fork it.
