### ISSUE TITLE
Old Torrents and User Profiles

### ISSUE THREAD

**Issue by yiiTT** [ewhal/nyaa#198]
When viewing an old torrent it should display the old uploader's username with a link that is similar to "nyaa.pantsu.cat/user/[user_id]/[username]". The URL scheme I propose would be "nyaa.pantsu.cat/user/old/[username]" and it should also accept everything that a normal user profile would have (except following a user?).

You would check if the [user_id] = "old" and then more or less handle it as user with the torrents from "user_uploads_old".

When an old username gets merged/takes control of old torrents #174 the "nyaa.pantsu.cat/user/old/[username]" URL should redirect to the current user "nyaa.pantsu.cat/user/[user_id]/[username]" while keeping the arguments in the URL.

**Comment by toynbeeidea** [comment]
I can tell you right off the bat that my old Nyaa username is totally different from my NyaaPantsu username, so that wouldn't work for me.

**Comment by yiiTT** [comment]
This feature would not work well anymore with how we do things.
