### ISSUE TITLE
Night mode does not theme the member menu

### ISSUE THREAD

**Issue by ripdog** [ewhal/nyaa#199]
<img width="218" alt="nightmode" src="https://cloud.githubusercontent.com/assets/174944/25835213/03026ef2-34d1-11e7-8a88-eb87ef1b7f63.PNG">

Firefox Nightly 55, Win10

**Comment by yiiTT** [comment]
Night theme moves top search bar due to span.search_text's contents "Search" **and** also keep the switcher in the same location to prevent further issues with alignment and increase usability.

![](http://i.imgur.com/C6zS277.png)
![](http://i.imgur.com/e5rFSHK.png)

**Comment by ripdog** [comment]
Fixed with #205
