### ISSUE TITLE
Night theme related issues

### ISSUE THREAD

**Issue by tomleb** [ewhal/nyaa#200]
Let's keep track of night theme issues here.
Issues:
- Member menu doesn't have a night theme yet. See picture [here](https://my.mixtape.moe/aysicz.png)

**Comment by yiiTT** [comment]
Night theme moves top search bar due to span.search_text's contents "Search" **and** also keep the switcher in the same location to prevent further issues with alignment and increase usability.

![](http://i.imgur.com/C6zS277.png)
![](http://i.imgur.com/e5rFSHK.png)

**Comment by tomleb** [comment]
Wasn't the top search bar issue solved in [#185](https://github.com/ewhal/nyaa/issues/185) ?

**Comment by aerojun** [comment]
Btw, the height of the navbar on the night theme is smaller.

**Comment by ripdog** [comment]
With #205, night mode no longer affects layout at all. The profile page is incomplete, so not much point theming it yet.

**Comment by kipukun** [comment]
Pretty sure this can be closed as of recent commits. Thanks to @ripdog, night theme doesn't affect layout anymore. Any bugs in layout is a core CSS issue, not a night theme one.

**Comment by Librarianaar** [comment]
Still seems to be affecting the layout for me, there's no clickable location for me to revert to day theme either. 

The biggest issue is without a doubt Megumin being obstructed though. 

<img width="927" alt="ss" src="https://cloud.githubusercontent.com/assets/28579920/25876304/26182f06-3514-11e7-8311-28a535ffe81e.png">

**Comment by kipukun** [comment]
That's fixed in the latest HEAD @Librarianaar, don't you worry ❤️ 

(This can be closed).
