### ISSUE TITLE
Remove users that took old user's username and put a stop to it

### ISSUE THREAD

**Issue by yiiTT** [ewhal/nyaa#208]
Currently there is no blocking in place to stop people from stealing usernames that previously uploaded torrents and/or commented. 

There should be a check in place on the "user_uploads_old" table during registration to stop this, and can also be expanded to "comments_old".

Then to finish it off do a purge on any existing user that stole a old username. (administration panel/tools?)

**Comment by alucard0134** [comment]
shit man but alucard

**Comment by yiiTT** [comment]
[Here](https://gist.github.com/yiiTT/e6b866cb3da3dbd434cead0c3253c9d5) is a break down of old user stats.

**Comment by yiiTT** [comment]
Ahh well we will handle it by hand if they are a good sized release group/uploader.
