### ISSUE TITLE
Invisible label in night version of site

### ISSUE THREAD

**Issue by DCNick3** [ewhal/nyaa#209]
When using night version in profile, "No torrents uploaded" label isn't visible, because of underfined background value of .profile-content 
![image](https://cloud.githubusercontent.com/assets/10363282/25849908/0433cb34-34c9-11e7-941b-25d5a584c7e2.png)
![image](https://cloud.githubusercontent.com/assets/10363282/25849850/cab98074-34c8-11e7-9b84-3fe0bafcc3f9.png)

**Comment by S0X-LT** [comment]
You should've mentioned this in the dedicated thread for night theme issues (#200).

**Comment by ayame-git** [comment]
Fixed in #213
