### ISSUE TITLE
Security issues?

### ISSUE THREAD

**Issue by 0rp3u** [ewhal/nyaa#215]
A quick look at the code suggest that you are not hashing the user's password, instead, you are hashing his email and using md5.
You should never save passwords in plain text, you should save a salted hashed version and the salt, also don't use md5, use sha-3.

a quick look, so maybe I am wrong.

**Comment by majestrate** [comment]
probably not hashed yet. proper hash+salting should for sure be added.

**Comment by sfan5** [comment]
We are using md5 for gravatar (which I want removed anyway because it's cancer).
Passwords are stored using Bcrypt

just by the way: your suggestion is dangerous, don't just use a hash function to store peoples passwords, use something like bcrypt, scrapt or pbkdf2 if you must

**Comment by 0rp3u** [comment]
Upon closer inspection, i see a use of bcrypt, so it is actually good!
