### ISSUE TITLE
Format torrent descriptions

### ISSUE THREAD

**Issue by aerojun** [ewhal/nyaa#224]
The descriptions of the torrents can overflow the div and make it look bad.

E.g.:

https://nyaa.pantsu.cat/view/888404
http://i.imgur.com/Qa7i5ym.png

**Comment by yiiTT** [comment]
Looks like we just need to add "word-break: break-all;" to the description div. Is this also an issue with comments?

**Comment by aerojun** [comment]
@yiiTT I have not checked the comments, so i can't say for sure.

**Comment by aerojun** [comment]
I'm working a new design for the details. I hope to have it finished today.

**Comment by aerojun** [comment]
My proposal:

Torrent without description:
http://i.imgur.com/uE1bdVJ.png

With description (solving this issue):
http://i.imgur.com/iSQ65Zh.png
http://i.imgur.com/qtHAgDJ.png

If you like it i can make a PR.

**Comment by alucard0134** [comment]
go for it

**Comment by kipukun** [comment]
How does it look on mobile?

**Comment by tomleb** [comment]
Yup, make a PR

**Comment by aerojun** [comment]
@kipukun 

Mobile screenshot:
http://i.imgur.com/SNgr4sH.png

**Comment by aerojun** [comment]
PR was reverted for some reason. I think it's that i forgot the comments or so.

**Comment by aerojun** [comment]
Created new PR. If not reversed i'll close this issue.

**Comment by kipukun** [comment]
Your torrent description got applied. No need for a new PR.

**Comment by aerojun** [comment]
@kipukun I was talking about #289.
