### ISSUE TITLE
Trying to access torrents with IDs over 32-bit Integer limit yields blank page

### ISSUE THREAD

**Issue by ElegantMonkey** [ewhal/nyaa#227]
[On 2,147,483,647](https://nyaa.pantsu.cat/view/2147483647), it fails (although there's no Page not Found, but that's another problem).
[On 2,147,483,648](https://nyaa.pantsu.cat/view/2147483648), it succeds with a blank page.

**Comment by sfan5** [comment]
in the first example chromium complains about `ERR_INVALID_RESPONSE` so something else is very wrong.

**Comment by ElegantMonkey** [comment]
@sfan5, seems to be a problem with the NotFoundHandler usage on viewTorrentHandler.go. Using http.NotFound works, although it returns the stock 404 page.

**Comment by ElegantMonkey** [comment]
Removing the gzip handler from ViewTorrentHandler makes the 404 page appear on the first link, so I guess this is related to #236

**Comment by SpamNeko** [comment]
[https://github.com/ewhal/nyaa/pull/236](https://github.com/ewhal/nyaa/pull/236) Fixes both cases of this, in-range values were having header disagreements between gzip/notgzip, out-of-range values were actually returning 404, but with the blank torrent as the 404 pages.

**Comment by ElegantMonkey** [comment]
@SpamNeko, still happens to me, although now the first case gives a proper 404, the second one gives a blank page. Are you running SQLite? Maybe this is a Postgres specific problem, idk.

**Comment by SpamNeko** [comment]
Yes, I'm still running SQLite atm, and the second case works for me.

Strange, but I think it should work when combined with [https://github.com/ewhal/nyaa/pull/243](https://github.com/ewhal/nyaa/pull/243) since that turns the second case into the first case?

**Comment by ElegantMonkey** [comment]
Yeah, it should work, but I still think it's a kinda ugly workaround - gorm should have handled this.
