### ISSUE TITLE
Pagination not functioning in RSS feed

### ISSUE THREAD

**Issue by danejur** [ewhal/nyaa#249]
Right now it looks like the URL template for normal searches
>`https://nyaa.pantsu.cat/search/{page}?{query}`

doesn't translate to RSS feed "searches".

e.g.
>`https://nyaa.pantsu.cat/feed/{page}?{query}`

returns a 404. Pagination in these searches would be greatly appreciated.

**Comment by yiiTT** [comment]
+1 the feed should accept all arguments a search would

**Comment by akuma06** [comment]
Is the page argument really a thing? I don't see why would you need that :/. Except that the feed accept every arguments a search would

**Comment by danejur** [comment]
Important for me, as I use the RSS feature as an API for searching within an application. Way better than parsing HTML.

Alternatively, exposing a JSON API would work just as well.
