### ISSUE TITLE
File List

### ISSUE THREAD

**Issue by an-electric-sheep** [ewhal/nyaa#25]
Where available additional metadata such as number of files, file names, size, etc. would be very useful.

File names are important in the case of multi-file torrents, such as music albums or batch releases to see whether they include certain bonus material. Sizes give a rough hint at quality, absent other information.

**Comment by MasterCATZ** [comment]
would be nice to sort by file size / date / name

also does anyone know of a way to have the magnets also include a torrent file so hash checks / quick re-seeding  could be done at some other stage later on ?

**Comment by an-electric-sheep** [comment]
> also does anyone know of a way to have the magnets also include a torrent file 

That's called "downloading a torrent file". They often are several kilobytes in size, so they're too large for an URI.

**Comment by egozi44** [comment]
Will be nice if we could have the View files button again so we can see preview before download stuff again.

Does it even possible to retrieve the old list or it lost forever?
