### ISSUE TITLE
Small unintended bug on page

### ISSUE THREAD

**Issue by lod256** [ewhal/nyaa#250]
For some reason my video downloading extension trips on the page showing mp4 files named as magnet link.mp4. Screenshot here http://pasteboard.co/4qBJuqAs2.jpg not very important but doesn't happen on other web pages.

**Comment by sfan5** [comment]
likely caused by this in the magnet links:
![bildschirmfoto_2017-05-10_12-51-48](https://cloud.githubusercontent.com/assets/1042418/25895276/8283e314-357f-11e7-96c1-ca77d3fa3a19.png)

Report a bug to the extension author, this is not our fault.
