### ISSUE TITLE
Member button is invisible on IE10+

### ISSUE THREAD

**Issue by egozi44** [ewhal/nyaa#259]
So  the Memeber button is invisible on IE10, old nyaa.. was old.. and supported IE10 and 11 just fine xD
Any chance you can fix it?

![45645](https://cloud.githubusercontent.com/assets/14190834/25883710/806c1968-3555-11e7-8f11-f79f1c23bb51.PNG)

**Comment by S0X-LT** [comment]
Simple solution: don't use IE.
No really, You shouldn't be using IE at all. At least use Edge.

**Comment by egozi44** [comment]
I already said on other thread that I mix my browsers uses (use IE FF and chrome) depend on the situation, I want the site to work with all three common browsers if possible, also I can't and don't want to use edge, it just unfinished beta browser that come with os that risk your privacy and limit the things you can install on it for the sake of MS control :/

**Comment by avail** [comment]
Happens to me in latest chrome as well - I believe it's due to using a custom visual style which and the site's stylesheet lacking colouring for the element so it uses system colours.

**Comment by ripdog** [comment]
I can't see any reason this wouldn't work in IE 10. No unusual or new CSS techniques are used to colour that button. Indeed, the Member button does not have it's own colour, rather it's just transparent, inheriting its colour from `#mainmenu`. 

I just tested it on IE11 and it works fine. I don't have access to IE10 and I don't care.

@avail Something is wrong with your browser. I'd have a look around in the developer tools, turn off addons, and if still borked wipe your browser profile.

**Comment by egozi44** [comment]
In my IE the only addons I have are Google toolbar and ads blocker, nothing else.

tbh I tested the site with IE not long ago and recall the member button worked well till today

**Comment by alucard0134** [comment]
shit browser, wontfix

**Comment by egozi44** [comment]
I see :/

I know that some people out there hate that browser almost like cancer....
But there's still high percent of people who use it simply from the fact they have no idea how to use PC aside their daily uses (which ironically can also included visiting nyaa and download animes via torrents clients xD   )

**Comment by akuma06** [comment]
Might look into that when I go back from holidays, should be easy to fix...
