### ISSUE TITLE
RSS feeds

### ISSUE THREAD

**Issue by kipukun** [ewhal/nyaa#26]
RSS feeds for specific search queries.

**Comment by S0X-LT** [comment]
In my opinion, it's better to wait for torrent upload to be enabled before adding this. That was main purpose for the RSS feed after all, checking new uploads.

I'd also suggest to add Atom, no downside from having both, and is more feature rich than RSS.

**Comment by kipukun** [comment]
I agree. This can be kept open and worked on after enabling torrent upload.
Which would also require accounts, if we don't want to only have Anonymous uploads.
