### ISSUE TITLE
Email confirmation not sent

### ISSUE THREAD

**Issue by sdafsafds** [ewhal/nyaa#277]
Not in spam forlder

**Comment by junpet** [comment]
I have the same problem (@live.com).

**Comment by egozi44** [comment]
same here (@hotmail.com)

**Comment by thewisenerd** [comment]
same here (@protonmail.com)

**Comment by lc-guy** [comment]
same here (@gmail.com)

**Comment by yiiTT** [comment]
This feature is currently disabled/not in use.

**Comment by egozi44** [comment]
Hope it won't prevent us from making the same user in the future though (like telling us that user is already taken)

**Comment by alucard0134** [comment]
feature is working in repo, however it is not enabled in prod

invalidated
