### ISSUE TITLE
Make search more lenient

### ISSUE THREAD

**Issue by avail** [ewhal/nyaa#28]
someone on the IRC suggested https://github.com/blevesearch/bleve, which might be a good choice since base is already in Go.

Currently, the search takes everything for granted, so typing 'horrible kemono 1080', for example, would return no search results.

**Comment by akuma06** [comment]
Can't we just do a FullText search in description and title when we switch to another SQL Driver?

**Comment by romanrm** [comment]
You can enter horrible%kemono%1080 and this will give the expected result.

However on the original nyaa % were of course not required, and you could also enter words in any order.

**Comment by sfan5** [comment]
Since 4371be749407a90844d129b57428d4085adc3374 you can do keyword search like that, however a proper search engine should be considered

**Comment by SauSaurus** [comment]
I'd like to add that searching for torrent ID should also be a possibility. For example:
DmonHiro fansubs' blog links to http://www.nyaa.eu/?page=download&tid=240850, which is the same as https://nyaa.pantsu.cat/view/240850.
So searching for "240850" should return the torrent, making it easier to download torrents from dead links.

**Comment by HitmanJ** [comment]
Sorry if I'm writting this down on the wrong issue, but I think this is still on-topic.

I'd also recommend adding an "Exclude categories" from a search option. This could be a good alternative while we don't have accounts. On Nyaa we could change our settings so that certain categories wouldn't appear on the site.

**Comment by S0X-LT** [comment]
this is fixed
