### ISSUE TITLE
gravatar image used for profile picture

### ISSUE THREAD

**Issue by thewisenerd** [ewhal/nyaa#285]
iirc, email address in nyaa was private settings. having the profile picture from gravatar "slightly" decreases this.

**Comment by thewisenerd** [comment]
relevant: https://meta.stackexchange.com/questions/44717/is-gravatar-a-privacy-risk/44724

**Comment by thewisenerd** [comment]
the gravatar image address is simply `md5(mail)` ; it would be _possible_ to get the user's email with this information.

**Comment by yiiTT** [comment]
A good trick to get around this would be to set your email to myemail+anythingyouwant@site.com most email providers will offer this feature. You can also add "." to anywhere in the email and they will all get sent to your "myemail" email.

If you use google or outlook/hotmail this already works, and for yahoo enable and configure "Disposable Addresses"

**Comment by yiiTT** [comment]
@thewisenerd how does #379 sound?

**Comment by thewisenerd** [comment]
@yiiTT I'm already using an email of the form `mail+salt@site.com`, however, that's still a _trick_ . #379 sounds good.

**Comment by thewisenerd** [comment]
closing this in support of #379 .
