### ISSUE TITLE
New frontend design

### ISSUE THREAD

**Issue by avail** [ewhal/nyaa#29]

**Comment by avail** [comment]
Should we bother with supporting mobile phones? I could do a design quite easily without using any base framework (more lightweight), but it probably would not support mobile - unless someone helps in making it responsive

**Comment by aerojun** [comment]
Just wrapping the table with `<div class="table-responsive"></div>` should be good enough.

**Comment by SandroHc** [comment]
I believe mobile support is a must in any recent website.

**Comment by bakape** [comment]
Is the site going to be very light on JS? In that case simple media query CSS rules and minor HTML adjustments should make it mobile-friendly. I can do those.

**Comment by avail** [comment]
the plan is to not use any JS at all, hopefully.

**Comment by akuma06** [comment]
Yeah, no JS. If there is, it would be still usable without enabling it

**Comment by turbzz** [comment]
I do Frontend development for a living if you need some help :)

**Comment by avail** [comment]
@turbzz I've started on a frontend design, without any framework use, so it'll probably break horribly on mobile - if you would I'd appreciate some help with the mobile portion :] I can make a separate repository while it's WIP, so we don't spam this with commits

**Comment by aerojun** [comment]
It doesn't look that bad on mobile.

http://i.imgur.com/Jk7rBoI.png
http://i.imgur.com/eDIV01W.png
http://i.imgur.com/eDaI0Na.png

But it could be improved.

**Comment by avail** [comment]
@aerojun I'm completely remaking it, not reusing any of the old base.

**Comment by Jiro-Horikoshi** [comment]
@avail are you doing the web design, frontend code, are both? Me and a couple other guys actually started working on a new feature stacked frontend so we might be able to collaborate.

**Comment by alexhgian** [comment]
How about use a modern framework like React to build components but then for whatever reach they don't have javascript we use the concept of Progressive Enhancement to fall back to a server-side render version of the page.

**Comment by meh301** [comment]
@Jiro-Horikoshi like the concept but I think an excellent implementation would take time and might be better off as a sister site for the time being? (simple API to load feed from nyaapantsu idk I'm just a useless architect with minimal knowledge) I think a fast, simple, and functional site should be the current priority.

**Comment by gensuihime** [comment]
I'm interested in helping work the frontend as well as restore the original Nyaa theme. I read some comments above and I think that the original Nyaa should be restorable without the use of javascript. IIRC nyaa.se had a pretty simplistic design that I reckon can be recreated from something like bootstrap? Maybe. It may not need any framework at all.

As for mobile support I can also work on a simplified mobile frontend that can be improved later (right now the project is in its infant stages and I think functionality is top priority) Although personally it's safe to say that almost no one will be downloading torrents on their phone, so a whole mobile frontend seems unwarranted and is pretty low on the todo list. Simply making the default frontend work at a certain level on mobile devices will likely be enough.

**Comment by bakape** [comment]
I'm with @Jae on all points.

**Comment by Jiro-Horikoshi** [comment]
Since I'm responsible for coordinating all the frontend efforts, can everyone interested kindly email me at jiro.horikoshi1@gmail.com with your discord username? I'm thinking of making a discord channel with everyone involved.

**Comment by majestrate** [comment]
@Jiro-Horikoshi we already have an established and active irc channel on rizon, try submitting a seperate issue for discord.
in general, mo js mo problems

**Comment by Jiro-Horikoshi** [comment]
We're forking out and working on the frontend separately. Also:

- IRC doesn't like VPNs, which I have to use
- IRC doesn't have chatlogs
- IRC doesn't support integrations and isn't really something designed for team collaboration efforts

**Comment by ewhal** [comment]
@Jiro-Horikoshi your document/proposal is way out of scope of this project

**Comment by Jiro-Horikoshi** [comment]
The current people I have already said they will be happy to maintain it until they die.
Implicit: before we die we'll find new substitutions.
Consider us to be a separate team streamlined for frontend-related matters only.

**Comment by kipukun** [comment]
I'm _pretty_ sure this can be closed, since we do have a new frontend design. Small tweaks is all that's needed, really.
