### ISSUE TITLE
Few moderation system issues

### ISSUE THREAD

**Issue by tomleb** [ewhal/nyaa#303]
- The number of torrent reports link to ..?user_id= [https://my.mixtape.moe/nvmnmt.png](https://my.mixtape.moe/nvmnmt.png)
- Not sure if issue, a logged in user can report the same torrent many times.
- Reporting a torrent when logged in creates a new user.

**Comment by ayame-git** [comment]
1. That's intended
2. Idk
3. Fixed

**Comment by tomleb** [comment]
1. Why ?

**Comment by ayame-git** [comment]
1. It should redirect to list of torrents uploaded by said user, it doesn't work yet though
