### ISSUE TITLE
Fix bug when eager loading subcategory information

### ISSUE THREAD

**Issue by Lietzu** [ewhal/nyaa#32]
On every page load the following is printed to console:
`(can't preload field Sub_Categories for main.Categories) `

Although we aren't doing it yet, ostensibly this means displaying subcategory information on the main page will fail. This is related to all the query functions with Preload("Subcategories") in them. No idea what the exact problem is.

**Comment by akuma06** [comment]
Should be resolved with the last commit 👍

**Comment by ayame-git** [comment]
Fixed as of 667415d
