### ISSUE TITLE
Seach torrents by seeds/peers

### ISSUE THREAD

**Issue by tylrgamster14** [ewhal/nyaa#333]
one of the most helpful search filters that was on nyaa, it really helps find the best torrents when searching

**Comment by majestrate** [comment]
sort by swarm size?

**Comment by solinium** [comment]
I believe this is only possible if you run a tracker.

**Comment by S0X-LT** [comment]
Actually, this is doable. TPB doesn't run a tracker and it can still sort by number of seeds. 
This is currently a WIP btw.

**Comment by tylrgamster14** [comment]
pretty much what S0X-LT said, in the pic were it shows (date/seeders/leechers .ect ) i liked the fact i could click seeders and it would show torrents with the best seeds or if i searched for something i could do the same thing and it would show the best torrents out of my search.  
http://pic.accessify.com/thumbnails/777x423/f/files.nyaa.eu.png

**Comment by Miao14** [comment]
We are using tracker.doko.moe anyway for seeds/peers. (provided by me)

**Comment by majestrate** [comment]
added in https://github.com/ewhal/nyaa/commit/ffbba9d905c2f4532435701df49af6e8bebb03da

**Comment by S0X-LT** [comment]
It was added, but still borked atm, it does nothing. Actually, some features of the advanced search are broken due to still being in development.

**Comment by tylrgamster14** [comment]
in due time but thank you guys for listening to my idea/request, cant wait till the site is done.
