### ISSUE TITLE
Sukebei servers

### ISSUE THREAD

**Issue by egozi44** [ewhal/nyaa#366]
So I know that Sukebei being left undated on purpose for now but would it be possible to  at least fix the overlord/falling issue?

Sukebei may be undated atm but it still have many many torrents/magents from many things that you can't find on other places, and currently searching what you want on it is a pure nightmare not just because unlike PN it still undated and broken but also because it's servers will fall/overload any few seconds.

Would it be possible to at least fix it without update the database and any of the sort?

**Comment by S0X-LT** [comment]
It's still a WIP, just wait for it. We're focusing on having a stable version of Nyaa first, as committing changes to both sites is just too time consuming.

A stable version should be coming a couple hours after the main Developer wakes up. If everything goes according to plan of course, but even if not, it will just be a couple days.
