### ISSUE TITLE
Undefined DefaultLogger when building

### ISSUE THREAD

**Issue by aerojun** [ewhal/nyaa#373]
Using `go get` or `go build` throws the following error:

`./main.go:121: undefined: db.DefaultLogger`
`./main.go:121: too many arguments in call to db.GormInit
	have (*config.Config, <T>)
	want (*config.Config)`

**Comment by alucard0134** [comment]
cannot repro with go1.8.1 in prod

**Comment by sfan5** [comment]
me neither with go 1.8.1 from arch repos

**Comment by ayame-git** [comment]
Arch 4.10.11-1 builds just fine with go 1.8.1

**Comment by aerojun** [comment]
@alucard0134 @sfan5 I'm using go1.8.1 darwin/amd64 MacOS.
Commit: 8136f6371c648b4481ce14cffa4d9ccefafc3b32

**Comment by aerojun** [comment]
`git reset --hard` fixed the issue.
