### ISSUE TITLE
Need new report categories

### ISSUE THREAD

**Issue by toynbeeidea** [ewhal/nyaa#393]
I began the process of remaking all of my old torrents once Nyaa died, as the main tracker no longer existed, and in the case of older torrents, neither did the backups.  However, there is no way to flag an old torrent as deprecated, nor any way to flag duplicate torrents.  I can just mark as "illegal" or "spam."  I'll go with spam for now, I guess, but...

**Comment by sfan5** [comment]
we should have these at least:
* Wrong category
* Duplicate

**Comment by toynbeeidea** [comment]
Oh, and if we're gonna flag duplicates:  Maybe we need some way to indicate what the correct torrent ID is.  Like, if I upload an updated torrent, I don't want people to just mark my new torrent as the duplicate, I want the old torrent flagged as the dupe.

Though maybe a "deprecated" flag is enough.

**Comment by an-electric-sheep** [comment]
You can change the trackers of torrents without changing the infohash and thus without creating duplicates. So it should be possible to update torrents. At least in principle. But nyaa would need a way to mangle the torrent to add the new trackers.

**Comment by toynbeeidea** [comment]
an-electric-sheep:  A decent idea, but arguably a separate issue.
