### ISSUE TITLE
nyaa.si? o_o

### ISSUE THREAD

**Issue by egozi44** [ewhal/nyaa#406]
WTH... so there's another nyaa alternatives around or it still relate to you guys?

https://nyaa.si/

https://sukebei.nyaa.si/ 

Wonder if their sukebei is up to date

**Comment by DeadlySync** [comment]
Dunno about the "freshness" of the sukebei database, but no.
This nyaa.si - I think - has nothing to do with the guys here.
Also, nyaa.si uses python, and is quite a rush work at that.
I think Nyaa Pantsu has way more features than nyaa.si, but Pantsu servers are... well... weak. heh.

**Comment by ewhal** [comment]
Has nothing to do with us

**Comment by ayame-git** [comment]
Daaaaaaiiiiiiiiz

**Comment by egozi44** [comment]
I see~ guess it at least answer the people who want sukebi 

Maybe you can kindly ask/steal from them the sukebi database if they have the up to date one? ;D

**Comment by yiiTT** [comment]
@egozi44 It's not like we are forgetting about sukebei it's half the site. It will be worked on in the next few days, since there is some major code changes in-progress (remove gorm).

Also I believe our sukebei db is already as up-to-date as it can be, it just has to get updated into the main db file.

**Comment by egozi44** [comment]
> @egozi44 It's not like we are forgetting about sukebei it's half the site. It will be worked on in the next few days, since there is some major code changes in-progress (remove gorm).
Yea I'm aware of it, just meant it give answer to these who currently looking for some sukebei altervetives

> Also I believe our sukebei db is already as up-to-date as it can be, it just has to get updated into the main db file.

Really? so you were able to get the last database of 1 may 2017?  :o 
If yes it will be awesome

**Comment by akuma06** [comment]
And I think that they grabbed our sukebe database by the way (someone was really annoying on irc one day to get the sukebe db)

**Comment by Sa-Ja-Di** [comment]
Good to see that there are more replacement pages are upcoming, keep up the good work :)

**Comment by egozi44** [comment]
It also seem like some of the changes we suggested finally been released to the public version of the site.

One of the things that are still missing is the Remember me button
