### ISSUE TITLE
Change Unix Timestamp to Date

### ISSUE THREAD

**Issue by aerojun** [ewhal/nyaa#41]
The date at the torrent details is a timestamp.

**Comment by akuma06** [comment]
Yep and I would like to add that there is already a created_at, updated_at dates (generated by GROM) in the table.

**Comment by Lietzu** [comment]
The auto generated created_at and updated_at date columns were removed because SQLite doesn't actually support datetime, and there was an already existing date column on the scraped table.

**Comment by akuma06** [comment]
O-Oh ! You're right, completely forgot about that part x).
