### ISSUE TITLE
Migrate db from sqlite to something more "fitting"

### ISSUE THREAD

**Issue by KptCheeseWhiz** [ewhal/nyaa#43]
I can make an elastic search api server which would help with storing and finding torrents.

Reply to this issue to give me the go or just close it :3

**Comment by kipukun** [comment]
Possible candidate: https://github.com/boltdb/bolt

**Comment by Zer0-** [comment]
What's wrong with SQLite? It's fast, portable and very easy to deploy.

**Comment by akuma06** [comment]
Yes but the big problem of SQLite is the write operations. It allows only one single write*operating to take place at any given time, hence allowing a limited throughput.

Comparison between https://www.digitalocean.com/community/tutorials/sqlite-vs-mysql-vs-postgresql-a-comparison-of-relational-database-management-systems

**Comment by aerojun** [comment]
We could use Mysql/MariaDB + Redis as cache

**Comment by Lietzu** [comment]
I am, at the moment, planning to transfer stuff to MySQL sometime this weekend. Possibly the user version of the DB may continue being SQLite, if conversion turns out to be easy, but I would like to talk about alternatives too.

**Comment by kipukun** [comment]
Having everything in MySQL may make it easier to deploy and manage, but of course _**it is a mystery**_

**Comment by bakape** [comment]
MySQL will however encumber others setting up their own mirrors. There is a great advantage in one binary distribution with little to no configuration.

As an alternative, BoltDB is a good choice and performs well with concurrent reads and writes, but it's a key-value store. For querying you'd probably want indexes and a query builder, so how about https://github.com/timshannon/bolthold?

**Comment by bakape** [comment]
There is also http://www.blevesearch.com/ as an embedded alternative to elasticsearch.

**Comment by Mithgol** [comment]
@akuma06 

> Yes but the big problem of SQLite is the write operations. It allows only one single write*operating to take place at any given time, hence allowing a limited throughput.

Does Nyaa/Pantsu reall perform so many write operations that it becomes a limitation? On a non-SSD drive at 7200RPM SQLite performs [about 60 transactions per second](http://sqlite.org/faq.html#q19).

**Comment by Lietzu** [comment]
Well we've been superceded and it's getting transferred to postgresql, I guess. I'd still like to do some work on it for adding the new stuff though (comments and account stuff).

**Comment by MasterCATZ** [comment]
My database backup of nyaa was in PostgreSQL

but I normally use MariaDB

**Comment by kkartaltepe** [comment]
>Does Nyaa/Pantsu really perform so many write operations that it becomes a limitation? On a non-SSD drive at 7200RPM SQLite performs about 60 transactions per second.

>When any process wants to write, it must lock the entire database file for the duration of its update

I think you can squeeze out some more write performance by switching to WAL mode in sqlite but its really cant support any kind of serious read/write workload.

**Comment by ewhal** [comment]
We support postgres now
