### ISSUE TITLE
Possible Integrity Issue with Sukebei Categories

### ISSUE THREAD

**Issue by yetanotheranon** [ewhal/nyaa#455]
Hey pantsu dev, it looks like there could be some possible integrity issues with the sukebei categories. I see someone said in the /g/ thread that there is a known category issue, but didn't elaborate on exactly what it is so maybe I am just reporting something already known. 

Anyways when search for the visual novel "辻堂さんの純愛ロード" (which is Tsujidou-san's Pure Love Road, but you search sukebei using moonrunes), the results that show are under "Lossless Audio". When searching nyaa.si with the same moonrunes, the results are pretty much the same except they come as "Games" which is the correct category for them.

I have also found another example where searching for "Imouto Paradise" brings up the OVA episodes as in the category "Software -- Application"

**Comment by akuma06** [comment]
Already reported: #162 #173
