### ISSUE TITLE
Make sorting by table column headers easier to spot

### ISSUE THREAD

**Issue by nakedloli** [ewhal/nyaa#484]
The swap was quite subtle so people might have missed the change  @SpamNeko 

https://puu.sh/vPKiI/336db2c474.png

**Comment by SpamNeko** [comment]
[what do](http://puu.sh/vPNUv/56d6587a50.png)

This abortive attempt uses (rubbish) images. Some kind of CSS arrows are probably the way to go? Apparently they are a thing.

**Comment by loadletter** [comment]
Unicode arrows plus CSS
http://stackoverflow.com/questions/2701192/what-characters-can-be-used-for-up-down-triangle-arrow-without-stem-for-displa

**Comment by x9zb** [comment]
It would look better if s/l/d counters had their own separate columns. 
Here's a mockup I did in photoshop using the unicode arrows as the indicators.  

![mockup](https://qt.vidyagam.es/JjsRWFN.png)

**Comment by SpamNeko** [comment]
Thanks for the tip @loadletter , first attempt is [this](https://github.com/ewhal/nyaa/pull/504) [image](http://puu.sh/vPZ22/422ab1ef6d.png), the logic works but obviously the arrows don't fit the layout, and they are super narrow to try to fit.

I really like the look of @x9zb mockup, I can probably rejigger the layout and arrows to match that if people agree?

**Comment by lc-guy** [comment]
@SpamNeko the mockup looks pretty good, so I'd say do it personally

**Comment by SpamNeko** [comment]
[Done](https://github.com/ewhal/nyaa/pull/504)
