### ISSUE TITLE
A question asked on 2.ch - sukebei and nyaa having the same categorisations 

### ISSUE THREAD

**Issue by nakedloli** [ewhal/nyaa#500]
A Japanese anon in the /g/ thread helped convey the site status to the japanese on 2.ch, as well as translate the questions asked by them.

This is one of the questions that were asked on 2.ch.

" sukebei and nyaa have identical categorisations, is that intentional?"
"The current sukebei is identical to nyaa with anime, audio, literature, live action, picture, and software."

**Comment by nakedloli** [comment]
#485

**Comment by nakedloli** [comment]
#485

**Comment by yiiTT** [comment]
#173
