### ISSUE TITLE
Status (Remake, trusted, a-plus) indicator bar on torrent page looks ugly

### ISSUE THREAD

**Issue by dumbwanker** [ewhal/nyaa#548]
Currently looks like this:

![](https://i.imgur.com/nokRpRn.png)

A few suggestions for changes:

1. Color the background

![](https://i.imgur.com/4FZuttb.png)

2. Add something to the sidebar

![](https://i.imgur.com/2v6p76F.png)

3. Color the content bit, like the original nyaa did

![](https://i.imgur.com/HCGkegs.png)

**Comment by aerojun** [comment]
I was thinking about this yesterday. Also, i was thinking about moving the uploader name and Category image to the right side.

I want to hear your opinions.

**Comment by dumbwanker** [comment]
Hm, I guess it could work, but
* It seems like this project is trying to be as similar to the original as can be, so the transition between the original and this version is less jarring. The original had this information on the left. Moving it would just make it confusing imo, but people would get over it given time
* Another thing to consider is the right side getting too big that there's barely anything on the left if the uploader decides to add a short description or no description at all. In that case, all that would be doing is making people scroll pointlessly through lots of whitespace on half the page

Though, I guess it would look nicer if that were on the right
