### ISSUE TITLE
Uploaded torrents must not contain private flag

### ISSUE THREAD

**Issue by an-electric-sheep** [ewhal/nyaa#69]
Magnets and DHT do not work for torrents that contain the private flag. Since people occasionally create those even for public distribution there needs to be a way to deal with them.

At least we need to survey what percentage of the data is affected.

**Comment by sfan5** [comment]
Did nyaa even allow you to upload private torrents?

**Comment by S0X-LT** [comment]
No, it didn't, IIRC it displayed the "Teapot" error message. When upload is enabled, disable upload of torrents with the private flag.

**Comment by ewhal** [comment]
Not a bug
