### ISSUE TITLE
About torrents, mangents, and FAQ (?)

### ISSUE THREAD

**Issue by egozi44** [ewhal/nyaa#71]
So it seem you managed to get most of nyaa back, but my main question is, if you going to let people upload torrents again in the future or at least add magnet links, TPB proved that you can still show seeders/peers and files previews (at least before their last fall in 2015) even when you don't use trackers (I think...).

 As for the FAQ it saying in the last line that "nyaa.pantsu.cat and sukebei.pantsu.cat do not host any files."..... is it mean that the FAQ still not finish (as it seem to be only title of unfinished subject) or that you completely gave up on let people upload stuff and pantsu nyaa will be simple magnet archive for old torrents without even having the option to add new contact?

**Comment by egozi44** [comment]
btw can these sites help you in any way to retrieve the database? (probably not but oh well)

https://web.archive.org/web/*/http://sukebei.nyaa.se/

https://archive.is/

**Comment by sfan5** [comment]
>if you going to let people upload torrents again in the future

Yes
>nyaa.pantsu.cat and sukebei.pantsu.cat do not host any files

This is referring to the fact that @ewhal does not want to host `.torrent` files on his server as that opens up additional concerns about legality we'd like to avoid.
(And also generally that it doesn't host any of the torrents contents for people ignoring about how BitTorrent works)

> btw can these sites help you in any way to retrieve the database? 

No

**Comment by akuma06** [comment]
And yes we can retrieve seed/leech stats of a torrent without having a tracker of our own. It suffices to scrap it :p. That's how many website linking torrents work.

**Comment by egozi44** [comment]
I see, thanks,

This one just confused me a bit however




>     if you going to let people upload torrents again in the future
> 
> Yes

> This is referring to the fact that @ewhal does not want to host .torrent files on his server as that opens up additional concerns about legality we'd like to avoid.
> (And also generally that it doesn't host any of the torrents contents for people ignorant about how BitTorrent works)

So you will let people upload torrents but they won't be directly uploaded to pantsu? or just you meant they will have different format at the end instead of .torrent? o_o

**Comment by sfan5** [comment]
We will let people upload torrents, maybe not as `.torrent` files itself but we will.
The site will then however still only server magnet links for each torrent.

**Comment by egozi44** [comment]
I see, thanks

**Comment by wranai** [comment]
I restored close to 200k anime torrents for archive.org. I haven't checked sukebei though (not very interested, sorry.)

**Comment by egozi44** [comment]
so archive.org did manged to help after all? 0.o

(also, what a waste, sukebi is important as normal nyaa is :0 )

**Comment by wranai** [comment]
archive.org is an open resource, nobody's stopping you from grab it all :) they scraped 694,153 urls from sukebei.{nyaa.se,nyaa.eu,nyaatorrents.info} at least once, 197,034 of which are downloads, 191,967 are info pages (view or torrentinfo), though some of those are duplicates and some are error pages or redirections. i can send you the jsons that the archive.org search returned
