### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by Ereza** [ewhal/nyaa#88]
You have chosen to use a .cat domain. Since the website is not directly related to the Catalan community nor translated into Catalan, the domain is likely to be suspended in the future, as the registry authority has already done in the past with other domains.

However, if you need a Catalan translation, we can help! The site should be prepared to accept multilanguage, and then we can translate anything you need! ;)

**Comment by sfan5** [comment]
I'm pretty sure that only applies to the top-level domains, which [is avilable](https://pantsu.cat/catalan.html) in Catalan.

**Comment by akuma06** [comment]
We could also make Nyaa support other languages. But that might be less prior for now, we still need user package and upload torrents before everything else

**Comment by ewhal** [comment]
translations would be neat but gotta do other things first

**Comment by Ereza** [comment]
@sfan5 You are probably right, the rules don't specify exactly what is required. While the registry authority says "considerable amount of content in Catalan", some registrars just ask to "publish a website which must be fully or partly in Catalan language". What "a website" is could be interpreted as just the base domain, if that's the case, you are right.

Anyway, if translations are added in the future, I'll be happy to contribute. Good luck with all other issues!

**Comment by ewhal** [comment]
@Ereza we have translation support now so if you'd like to translate it to catalan it'd be greatly appreciated

**Comment by Ereza** [comment]
@ewhal Done in #235. Thanks for letting me know! Keep up the good work!!

**Comment by HitmanJ** [comment]
Are you going to support more languages?

**Comment by sfan5** [comment]
We just need more translations

**Comment by HitmanJ** [comment]
I could help with English->Portuguese (Portugal) translations if needed.
